// 73 carrier hợp lệ — copy NGUYÊN VĂN từ sheet "Carrier Options" trong template chính thức
// của TikTok Seller Center. Sai một ký tự là TikTok từ chối cả file.
export const TIKTOK_CARRIERS: string[] = [
  ".Maersk.",
  "A. Duie Pyle",
  "AAA Cooper Transportation",
  "ABF Freight",
  "Amazon shipping + Amazon MCF",
  "Asendia US",
  "Averitt Express",
  "Better Trucks",
  "CDL",
  "Cainiao US",
  "Central Transport",
  "Ceva Logistics",
  "Cirro",
  "CrossCountry Freight Solutions",
  "DHL Heavyweight",
  "DHL eCommerce",
  "DHL express",
  "Day & Ross Freight",
  "Daylight Transport",
  "Dayton Freight Lines",
  "Deliver-it",
  "DeliverDirect",
  "DoorDash",
  "Easy Express",
  "Estes Express Lines",
  "Fastfrate Group",
  "FedEx",
  "Forwardair",
  "Freightquote by C.H. Robinson",
  "GLS US",
  "GLS USA",
  "GOFO.",
  "GPS",
  "Hovership",
  "JD Worldwide",
  "JP Express",
  "Jitsu",
  "LaserShip",
  "Lone Star Overnight",
  "Mainfreight",
  "Metropolitan",
  "OSM Worldwide",
  "Oak Harbor Freight Lines",
  "Old Dominion Freight Line USA",
  "OnTrac",
  "PS Logistics",
  "Pilot Freight Services",
  "Pitt Ohio",
  "R+L Carriers",
  "Roadie",
  "Roadrunner Freight",
  "Saia Inc.",
  "ShipX",
  "Southeastern Freight Lines",
  "Spee-Dee Delivery",
  "Speedx",
  "Sway",
  "SwiftX",
  "TForce",
  "Tax-Air",
  "Tazmanian Freight Systems",
  "Tusk Logistics",
  "UPS",
  "UPS Heavyweight",
  "USPS",
  "UniUni",
  "United Delivery Service",
  "Veho",
  "Weee",
  "Western Post",
  "XPO",
  "Xmiles",
  "Yanwen",
];

// Map tên carrier nhà in trả về → tên TikTok chấp nhận.
// Xếp từ CỤ THỂ đến TỔNG QUÁT: "DHL eCommerce" phải khớp trước "DHL".
const CARRIER_MAP: [RegExp, string][] = [
  [/dhl\s*(e-?com|ecommerce)/i, "DHL eCommerce"],
  [/dhl\s*express/i, "DHL express"],
  [/dhl\s*heavy/i, "DHL Heavyweight"],
  [/dhl/i, "DHL eCommerce"],
  [/ups\s*heavy/i, "UPS Heavyweight"],
  [/\bups\b/i, "UPS"],
  [/\busps\b|united states postal/i, "USPS"],
  [/fedex|fed\s*ex/i, "FedEx"],
  [/ontrac/i, "OnTrac"],
  [/osm/i, "OSM Worldwide"],
  [/lasership/i, "LaserShip"],
  [/gls\s*usa/i, "GLS USA"],
  [/\bgls\b/i, "GLS US"],
  [/asendia/i, "Asendia US"],
  [/uniuni/i, "UniUni"],
  [/veho/i, "Veho"],
  [/speedx/i, "Speedx"],
  [/swiftx/i, "SwiftX"],
  [/shipx/i, "ShipX"],
  [/jitsu/i, "Jitsu"],
  [/cirro/i, "Cirro"],
  [/amazon/i, "Amazon shipping + Amazon MCF"],
  [/cainiao/i, "Cainiao US"],
  [/yanwen/i, "Yanwen"],
  [/xmiles/i, "Xmiles"],
  [/roadie/i, "Roadie"],
  [/doordash/i, "DoorDash"],
  [/better\s*truck/i, "Better Trucks"],
  [/spee-?dee/i, "Spee-Dee Delivery"],
  [/lone\s*star/i, "Lone Star Overnight"],
  [/tforce/i, "TForce"],
  [/\bxpo\b/i, "XPO"],
  [/western\s*post/i, "Western Post"],
  [/hovership/i, "Hovership"],
  [/tusk/i, "Tusk Logistics"],
];

/**
 * Chuẩn hoá tên carrier về đúng tên TikTok chấp nhận.
 * Không nhận ra → trả về NGUYÊN VĂN tên gốc để người dùng tự sửa trong Excel,
 * KHÔNG bịa "USPS" — đoán sai carrier thì TikTok báo lỗi hoặc giao sai luồng.
 */
export function mapTiktokCarrier(raw: string): string {
  const s = (raw || "").trim();
  if (!s) return "";
  // Trùng khớp chính xác với danh sách chính thức → giữ nguyên
  const exact = TIKTOK_CARRIERS.find((c) => c.toLowerCase() === s.toLowerCase());
  if (exact) return exact;
  for (const [re, name] of CARRIER_MAP) if (re.test(s)) return name;
  return s;
}
